using Similar.Utility;
using System;

namespace Similar
{
	class Program
	{
		static void Main(string[] args)
		{
			var item1 = "Aside from this web based software being used as a paraphrasing tool or a text spinner, it can also be used as a vocabulary improvement tool.";

			// generated by quillbot.com
			var item2 = "This web-based program can be used as a text spinner or for paraphrase, but it can also be improved vocabulary.";

			var output = SimilarUtility.GetSimilar(item1, item2);

			Console.WriteLine("Item 1 reduced: " + output.Item1.Reduced);
			Console.WriteLine("Item 2 reduced: " + output.Item2.Reduced);
			Console.WriteLine("Same word count: " + output.SameCount);
			Console.WriteLine("Item 1 same percent: " + output.Item1.SamePercent);
			Console.WriteLine("Item 2 same percent: " + output.Item2.SamePercent);
		}
	}
}
